server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include=health,info,prometheus
  endpoint:
    prometheus:
      enabled=true
    health:
      show-details: always
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true