server:
  port: 8080
spring:
  output:
    ansi:
      enabled: always
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: my-java-app
    health:
      probes:
        enabled: true
      show-details: always
      livenessState:
        enabled: true
      readinessState:
        enabled: true

