apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-k8s-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rodrigonascimento001/java-k8s.git
    targetRevision: develop
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: java-k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
