name: build-test-deploy

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Docker image
        run: mvn -B spring-boot:build-image -Dspring-boot.build-image.imageName=springboot-kind-demo:ci

      - name: Set up git for push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Push manifests (git ops)
        run: |
          git config user.email "rodrigo_allexandre@yahoo.com.br"
          git config user.name "ci-bot"
          git add k8s/
          git commit -m "Update Kubernetes manifests [skip ci]" || echo "No changes"
          git push origin ${{ github.ref_name }}