name: CI/CD ArgoCD

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código fonte
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ Configurar JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # 3️⃣ Build do JAR
      - name: Build JAR
        run: mvn clean package -DskipTests

      # 4️⃣ Login no GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5️⃣ Build e push da imagem Docker
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker build -t ghcr.io/rodrigonascimento001/java-k8s/java-k8s:$IMAGE_TAG .
          docker push ghcr.io/rodrigonascimento001/java-k8s/java-k8s:$IMAGE_TAG

      # 6️⃣ Checkout do repositório de manifests
      - name: Checkout manifests repository
        uses: actions/checkout@v4
        with:
          repository: rodrigonascimento001/java-k8s-manifests
          token: ${{ secrets.GH_PAT }}
          path: java-k8s-manifests

      # 7️⃣ Atualizar imagem diretamente no deployment.yaml
      - name: Update image in deployment.yaml
        run: |
          sed -i "s|image: ghcr.io/rodrigonascimento001/java-k8s/java-k8s:.*|image: ghcr.io/rodrigonascimento001/java-k8s/java-k8s:$IMAGE_TAG|" my-app/deployment.yaml
          git add my-app/deployment.yaml
          git commit -m "Update image tag to $IMAGE_TAG"
          git push