name: CI/CD ArgoCD

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/my-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Update manifests repo
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@github.com"
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}-manifests.git
          cd ${{ github.event.repository.name }}-manifests
          kustomize edit set image my-app=ghcr.io/${{ github.repository }}/my-app:latest
          git commit -am "chore: update image to latest"
          git push
