name: CI/CD ArgoCD

on:
  push:
    branches:
      - develop

permissions:
  contents: write   # 🔑 Garante que o GITHUB_TOKEN pode dar push no repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/java-k8s:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Update manifests repo
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git checkout develop
          sed -i "s#ghcr.io.*/java-k8s:.*#ghcr.io/${{ github.repository_owner }}/java-k8s:latest#g" manifests/deployment.yaml
          git add manifests/deployment.yaml
          git commit -m "ci: update image to latest [skip ci]" || echo "No changes to commit"
          git push origin develop
