name: build-test-deploy

on:
  push:
    branches: [ "develop" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Docker image
        run: |
          docker build -t java-k8s:latest .

      - name: Push manifests (git ops)
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@example.com"
          
          # Garante que target/ nunca vai ser commitado
          echo -e "\n/target/" >> .gitignore

          # Adiciona apenas os manifests de Kubernetes
          git add k8s/
          git commit -m "Update manifests [skip ci]" || echo "No changes to commit"
          git push origin develop
